---
abstract: "Interface to CA's Workflow Automation AE (AutoSys Edition) job control."
author:
  - 'Douglas Wilson (dougw@cpan.org)'
build_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.133380'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: CA-WAAE
no_index:
  directory:
    - t
    - inc
requires:
  DBI: '0'
  Time::Piece: '0'
  constant: '1.04'
resources:
  repository: http://github.com/runrig/ca-waae.git
version: '0.03'
